### ISSUE TITLE
Can't get anything back but azure_ad_oauth2 ?

### ISSUE THREAD

**Issue by dupuis2387** [auth0/passport-azure-ad-oauth2#19]
this is probably a stupid question, but using the sample on the readme, I cant ever seem to get it to return any information back about the signed in user. all i ever get back is "azure_ad_oauth2". Do I then need to do manual requests to certain endpoints of the Microsoft Open Graph and try to get information about a user, from those arbitrary endpoints? 
In the azure portal for this login setup, the quickstarts show the use of MSAL.js, and just providing it the same information:

```

const msalConfig = {
   auth: {
     clientId: "my_code",
     authority: "https://login.microsoftonline.com/my_other_code",
     redirectURI: "http://localhost:3000/"
   },
....
```

it's somehow able to get a user's name, and a bunch of other information. Can that not be done here?

Edit: nvm. I'm an idiot. if anyone is ever in the same boat, http://www.passportjs.org/packages/passport-azure-oauth2/ worked for me and made sense

**Comment by spro** [comment]
To clarify this further, while `profile` in the `(token, refresh, profile, cb)` callback seems to only ever return `{provider: 'azure_ad_oauth2' }`, the `token` is in fact a JWT with useful information once you decode it.
