### ISSUE TITLE
v2 App Model support?

### ISSUE THREAD

**Issue by tusbar** [auth0/passport-azure-ad-oauth2#3]
Microsoft [just released](http://blogs.technet.com/b/ad/archive/2015/08/12/azure-ad-microsoft-account-preview-sign-in-personal-and-work-accounts-using-a-single-stack.aspx) the v2 App Model that allows SSO for both work/school and personal accounts.

Any plans to support it? :)

**Comment by clocked0ne** [comment]
+1
