### ISSUE TITLE
Make Readme more helpful

### ISSUE THREAD

**Issue by te-online** [auth0/passport-azure-ad-oauth2#4]
The readme of this repository is quite short and that is maybe good for getting started very fast.
But there are some additional steps necessary to get everything up and running – which you can hardly guess when you did not use passport or an OAuth Strategy for passport before.

-----

But first, I think there is an error in the code for using it with Azure AD (what this Strategy is for):
```
  var waadProfile = profile || jwt.decode(params.id_token, '', true);
```
needs to be something like
```
  var waadProfile = profile.upn || jwt.decode(params.id_token);
```

#### Argumentation

* The variable `profile` will always be set (thus being taken for assignment to waadProfile). While using with Azure AD, I discovered that `profile` will always be something like 
```
{
  "service": "oauthAzureAd..."
}
```
* What we want to use later on is the property `upn` (which translates to email-address of user that is authenticating – a universal identifier). So we could just check for `profile.upn`, because that is what we want?

* For jwt encoding you will need an additional package. (I used this https://github.com/auth0/node-jsonwebtoken). But I couldn't find one package that has a decode function that takes 3 arguments. Result: Remove the two last arguments.

* A last thing: As far as I know (please correct me if I am wrong :wink:) you not only need to decode the json-web-token, but you also need to verify it. This could be included in the example as well, if this is supposed to be a *best-practise*. (Source: https://azure.microsoft.com/en-us/documentation/articles/active-directory-authentication-scenarios/, see above the first *important* paragraph)

-----

The code snippets suggest that you can just copy and paste them, but that is not the case. Therefore my suggestion is to add annotations to the first code snippet similar to what I added below.

```
function (accessToken, refresh_token, params, profile, done) {
  // You will need a jwt-package like https://github.com/auth0/node-jsonwebtoken
  var waadProfile = profile.upn || jwt.decode(params.id_token);

  // This is just an example. Here you would provide a model *User* with the function *findOrCreate* that takes a callback function to be called when it is finished.
  User.findOrCreate({ id: waadProfile.upn }, function (err, user) {
    // Calling *done* is the most important. If err is not null, the server will most likely return 500. So just use it if there is something really wrong.
    done(err, user);
  });
}));
```

Maybe this helps to improve the Readme for people who encounter the same problems as me.

**Comment by siacomuzzi** [comment]
Hi @te-online , thanks for the details.

Do you mean that `profile.upn.upn` is a valid field? Could you please put a `console.log(profile)` and show me the output?

**Comment by siacomuzzi** [comment]
We need to decode `id_token` to get some user's info because currently we can't find a way to exchange access token by user info. See https://github.com/auth0/passport-azure-ad-oauth2/blob/master/lib/passport-azure-ad-oauth2/strategy.js#L102-L104

**Comment by te-online** [comment]
Oh, you are right. If `profile.upn` is set, it won't work at all. Maybe we could just swap `profile` and `jwt...` in the assignment, so that the information from the decoded jwt will be preferred?

Do you think it is a problem to get the user's info from the token?

**Comment by te-online** [comment]
Okay, I understand what you mean.

It would be great to have that stated in the Readme as well, wouldn't it? (At least as long as there is no implementation that uses `profile`.)

**Comment by siacomuzzi** [comment]
I just updated readme.md

thanks for the feedback!

**Comment by te-online** [comment]
Thanks! :relaxed: I am sure this will help.
