### ISSUE TITLE
Verification of token?

### ISSUE THREAD

**Issue by te-online** [auth0/passport-azure-ad-oauth2#5]
Hi! 

When we get the access token from Azure AD, doesn't it need to be verified instead of only encoded? I'm not sure about that at all, *especially* after reading all the docs from Microsoft. E.g. https://msdn.microsoft.com/en-us/library/azure/dn645542.aspx and https://msdn.microsoft.com/en-us/library/office/fp179819.aspx

Maybe someone can help me there. :blush:

**Comment by siacomuzzi** [comment]
If you want, you can decode + verify the token:

```
var decoded = jwt.verify(params.id_token, '{YOUR_CLIENT_SECRET}');
```

But a better solution could be using the `state` parameter (_this parameter is used as a mitigation against cross-site request forgery (CSRF) attacks_):

_If a state parameter is included in the request, the same value should appear in the response. The application should verify that the state values in the request and response are identical. For more information, see [Best Practices for OAuth 2.0 in Azure AD](https://msdn.microsoft.com/en-us/library/azure/dn645536.aspx)._

**Comment by te-online** [comment]
@siacomuzzi Thanks for the heads up and the idea to use the state parameter. 

I find it a bit confusing that you *can* verify the token, but many people just don't seem to care. There is no warning in any documentation, that you obviously *have* to use some type of verification, since a jwt is easy to create for anyone. And if I don't verify your jwts anyone can login to my application with any valid userid, right? 

The problem is that I already have the key verification in place – but missing one part I'm stuck with. Microsoft provides their public keys in an xml-file als plain text (I don't know which key-format...). But the jwt-library expects a pem-formatted key. I have no clue how to do this conversion... :-( 

– But this isn't a problem with this middleware, so I'm going to close this.
