### ISSUE TITLE
Domain hinting

### ISSUE THREAD

**Issue by petja** [auth0/passport-azure-ad-oauth2#9]
Could it be possible to have _domain hinting_ as described on the the table found from link below?

https://msdn.microsoft.com/en-us/library/azure/dn645542.aspx

It adds `domain_hint` parameter to sign-in url which, in my case, would redirect to on-premise login page.

Thank you.

**Comment by siacomuzzi** [comment]
You can override the [authorizationParams](https://github.com/auth0/passport-azure-ad-oauth2/blob/master/lib/passport-azure-ad-oauth2/strategy.js#L107-L117) method:

```
strategy.authorizationParams = function (options) {
  var params = {};

  if ('domain_hint' in options) {
    params.domain_hint = options.domain_hint;
  }

  return params;
};
```

**Comment by petja** [comment]
Great. It works :)

**Comment by lacicloud** [comment]
Hiya, 

I am trying to do the same for state but I am not sure where to add this code? I am creating a new strategy =  new AzureAdOAuth2Strategy ... with options and adding the state option there. Where should I add this override? 

Thanks

**Comment by siacomuzzi** [comment]
That `state` value is an option of the `passport.authenticate` method. See https://stackoverflow.com/questions/13788107/how-can-i-access-oauths-state-parameter-using-passport-js
